### ISSUE TITLE
Cannot create a fresh map

### ISSUE THREAD

**Issue by runlow** [ioan-chera/eureka-editor#18]
**Expected:**
Going to File -> Fresh map should bring up a dialog box which should allow creating another map in the wad.

**Actual:**
A dialog does open but it only has one input box. Changing the text string in it and pressing enter doesn't do anything.
There's no "OK" button anywhere on the interface.

New-map-related options behave very similarly (dialog only has a text input box) so perhaps the other options are affected the same way:
- Fresh Map (already mentioned)
- Copy Map
- Rename Map

![2021-01-21-162616_489x457_scrot](https://user-images.githubusercontent.com/2176657/105380650-0a760d00-5c06-11eb-9992-b17e5e460bc9.png)
Everything else in the editor seems to be working fine.

Using Eureka 1.27b
Tested it on Archlinux with the rapoison window manager.

A workaround I'm using is creating new map lumps in another program and then editing the new maps in the wad in Eureka (it works) but that's not very convenient.

It doesn't seem to output any errors to STDOUT or STDERR when this happens.

**Possible solutions:**
- I could maybe try an older version and try to pinpoint which commit introduced this problem
- the editor works fine other than this and so does every dialog box in it but there's an off chance that the ratpoison window manager is somehow doing this so I could try it on a different WM

**Comment by runlow** [comment]
What Fresh/Copy/Rename seem to have in common is that they all have references to `UI_ChooseMap`

**Comment by ioan-chera** [comment]
It's a bit odd because the dialog would always generate buttons such as OK and Cancel. Does this happen with the latest master build too?

**Comment by runlow** [comment]
Just tested it now.

Yes it does still happen when I build the latest master.

Fresh/Copy/Rename open a dialog like on the screenshot.

Are you able to reproduce this issue? Could you screenshot what the "Fresh map" dialog looks like for you on a Linux build and post your window manager?

Could it be that unlike the rest of the dialog boxes - these three rely on the window manager? I been trying to pinpoint what makes them different from the rest but haven't been able to figure it out yet.

**Comment by runlow** [comment]
Could someone please see if they can reproduce this bug on a Linux build?

**Comment by ioan-chera** [comment]
Then I guess I should build an Arch Linux virtual machine with your mentioned desktop environment. I hope it's not too much work to do.

**Comment by runlow** [comment]
There should not be that much difference between different Linux distributions for them to be relevant for the UI. I think it may be more relevant which window manager is used. Since you tested it on Xubuntu - I'm guessing you were running XFCE as your window manager. Was the "Fresh map" working OK when you tested it?

There may be no need for you testing it on Archlinux and ratpoison. It could be much work if you're not familiar with them. Consider testing it on the Manjaro distro if you want to - as it's based on Archlinux but has most things (including the WM) pre-configured.

**Comment by runlow** [comment]
Installed XFCE4 and tested Eureka, and now "Fresh map" works!

Strange.

![2021-02-28-111916_1637x868_scrot](https://user-images.githubusercontent.com/2176657/109416554-e224bf80-79b6-11eb-8431-84259908217b.png)

**Comment by runlow** [comment]
This workaround will do for now but long-term I'd rather not have to start xfce4 just for those 3 menu options.

There's the greater problem of not only OS but window-manager/desktop-environment compatibility. FLTK claims to be cross-platform - so if I understand it correctly - running a different WM should not be necessary. Especially given that all the other dialogs work.

**Comment by ioan-chera** [comment]
> People who want to make zdoom maps would probably not use Eureka to begin with but rather something like UDB or Slade.

I disagree with that personally. On macOS I cannot use UDB, and I prefer Eureka to SLADE, so I'd still use Eureka for Eternity UDMF maps for example. I _will_ prioritize the bugs anyway, and this example is indeed a bug to fix.

**Comment by ioan-chera** [comment]
I've fixed it on my end. I managed to run `ratpoison` in Xubuntu. @runlow, let me know if it works for you as well now.

**Comment by runlow** [comment]
@ioan-chera built b188f2391a500d9d with `cmake`
I'm afraid it's still the same as it was before.

Do you mean you managed to open and use *File -> Fresh Map* while running newest Eureka in `ratpoison`? For me it's still like in that screenshot. `Map Slot: [ MAP02 ]` and that's it - unless I run it in xfce4 - then it seems OK.

Were you able to reproduce the bug before fixing it for your setup?

Was `ratpoison` the sole window manager or did you run it on top of another one like xfce4? Were you using `.xinitrc` or are you using a login manager to start `ratpoison`? (I think the default one on xubuntu is `lightdm`).

Could you take a screenshot of "Fresh Map" on ratpoison? (press *Ctrl + T* then *!* then type in `scrot` but it needs to be installed)

Every other dialog works fine except for those three so I might later run through those dialog boxes with a fine comb to find out what it is exactly that breaks them. Sorry for not responding earlier.

**Comment by runlow** [comment]
Today I've noticed something even more bizarre which could be related.

When I tried b188f2391a500d9ddbf2 in `ratpoison` - everything worked fine (except for the issue reported here) but a new problem came up which was not there before.

I can no longer see textures for one-sided linedefs in b188f2391a500d9ddbf2. On the [older v1.27b version which built via AUR](https://aur.archlinux.org/packages/eureka/) a while ago - I was able to see them fine.

I'll take a screenshot to show what I mean.

**Comment by ioan-chera** [comment]
Yes, I was able to reproduce the initial problem (with the broken dialog boxes) with Ratpoison. I enabled this desktop environment in Xubuntu by following [this tutorial](https://theitcrow.wordpress.com/2011/03/23/the-ratpoison-tutorial-part-1/). Most notably, I added the `/usr/share/xsessions/ratpoison.desktop` file with that content, then logged out and back in with the Ratpoison option in the menu at the top-right of the login screen.

It was caused by the unusual way FLTK programs define their GUI programmatically. Instead of having an intuitive "create container, add container to window, create a button, add button to container" mode, it works like "create a container and begin a global context, create a button and it automatically becomes part of container, create other controls and they also become part of container, finally end the global context". I don't know if this is broken in itself though. I might be tempted to customize FLTK at some point, but right now I'm sticking to stock FLTK. What caused your problem was a call to `Fl::focus` in the middle of this creation process, which somehow inhibited the creation of further controls in Ratpoison. What I did was try to disable it during Ratpoison. Problem is that I depended on some environment variables which I'm not sure are on your system. They're `DESKTOP_SESSION` and `GDM_SESSION`. Do you have them set to `ratpoison`? If not, it means I must find other ways to detect the manager, or just remove `Fl::focus` from there, because those cases work without it anyway.

As for the 1-sided texture not showing, that may be one of the many regressions caused by my code changing spree (I really should have started writing unit tests before going on a spree, but I acted like an amateur here). Might be something similar, I'll see.

**Comment by ioan-chera** [comment]
@runlow Let me know if either of these still happens:

1. The missing dialog box controls
2. The missing midtex tile from the sidedef panel.

Regarding 2, it was caused because the XY origin is different in Ratpoison compared to other desktops!

**Comment by runlow** [comment]
It works! Can open both 1) "Fresh map" and can see the 2) midtex tile now in ratpoison! Thanks so much!

> They're DESKTOP_SESSION and GDM_SESSION. Do you have them set to ratpoison?

Neither are set for me. I don't use GDM (Gnome Display Manager) or any display manager. I'm afraid I don't know what would be a good way to detect if `ratpoison` is running. Removing calls to `Fl::focus` if they aren't needed sounds like a better solution to me although I'm not familiar with FLTK

I suppose I'll close the issue. Big thanks again, and thanks for the extra info - it should help in case anything like this comes up again. This is really great because I don't have to use other programs now for creating new maps or moving them.

**Comment by runlow** [comment]
@ioan-chera by the way, if still interested or if this comes up in the future http://ratpoison.nongnu.org/doc/Command-Line-Arguments.html#:~:text=environment

There is a `$RATPOISON` environment variable. I think it's pretty safe to assume that when it is set one is running `ratpoison`
